### ISSUE TITLE
For the item page, replace the UL with a Table

### ISSUE THREAD

**Issue by crass-public** [joshuawjulian/quarmdb#5]
The item page is extremely useful for findings specific items and which mobs drop them. The item page is currently very useful for identifying items that may drop off a particular mob. Unfortunately, the item page is not useful when you're trying to compare the drop rate of an item against many mobs.

Take the example of "Words of Possession"
https://www.quarmdb.com/items/11815/words-of-possession

This item drops from over 200 NPCs. Many of the NPCs drop this item at a separate rate:
- A Gorging Brute (1.24%)
- Lesser Icebone Skeleton (1.96%)
- etc

Right now there is no way to determine the drop rate without clicking on each NPC entry manually. Furthermore, it would be good to know the mob level range associated with each entry.

Please change the UL of NPC names, to include the drop %, and the level range, and zone of the mob.

Thank you!

**Comment by joshuawjulian** [comment]
Done for drops.

**Comment by crass-public** [comment]
Looks so much better already! Thank you.

One tiny nit, the column is sorting as a string, not as a numeric value:

For instance: https://www.quarmdb.com/items/10035/ruby you can see 11% in the 1% range.

**Comment by joshuawjulian** [comment]
Thank you. Check it again please before I close!

**Comment by crass-public** [comment]
@joshuawjulian It's still sorting by leading character instead of number for me. I tried in both Chrome & Firefox, with private browsing sessions to rule out cached copies.

**Comment by joshuawjulian** [comment]
@crass-public My bad forgot to push the code, should be building now
https://github.com/joshuawjulian/quarmdb/commit/0e53f3328278ba630a590f5c3641d3ba3d7b2e82
All chances for the same NPC id are the same so I just take first one

**Comment by crass-public** [comment]
@joshuawjulian That did the trick! Looking great now. Appreciate your work on this one, it's a huge QOL improvement.

**Comment by joshuawjulian** [comment]
Just want people to enjoy the search and I want to break off rust. Thanks for the feedback!
